// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixwvsptwxhvgszplbwoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4d3ZzcHR3eGh2Z3N6cGxid29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjgxMjEsImV4cCI6MjA1ODg0NDEyMX0.2pdDfZxB5C09BjFN6XLPwgYqa0np_Foh0Mbow9VyKJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);